# Generated by Django 4.0.3 on 2022-03-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
