# Generated by Django 4.0.3 on 2022-08-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_task_status_tuestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TUEStatus',
        ),
    ]
