# Generated by Django 4.0.3 on 2022-08-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_filesupload_status_filesupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesupload',
            name='status',
            field=models.CharField(choices=[('Stage 1', 'Stage 1'), ('Stage 2', 'Stage 2'), ('Stage 3', 'Stage 3'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=200, null=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name='filesupload',
            order_with_respect_to='user',
        ),
    ]
