# Generated by Django 4.0.3 on 2022-08-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_filesupload_status'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='filesupload',
            order_with_respect_to=None,
        ),
    ]
