# Generated by Django 4.0.3 on 2022-08-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_filesupload_status_sts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sts',
            name='user',
        ),
    ]
