# Generated by Django 4.0.3 on 2022-08-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_sts_user'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='sts',
            order_with_respect_to='user',
        ),
    ]
