# Generated by Django 3.0.5 on 2022-08-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_sts_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sts',
            name='status',
            field=models.CharField(choices=[('in Stage 1', 'in Stage 1'), ('in Stage 2', 'in Stage 2'), ('in Stage 3', 'in Stage 3'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='in Stage 0', max_length=200, null=True),
        ),
    ]
