# Generated by Django 3.0.5 on 2022-08-10 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0019_auto_20220810_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='sts',
            name='user_id',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='sts',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='sts',
            name='user',
        ),
    ]
