# Generated by Django 3.0.5 on 2022-08-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_tueform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tueform',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
