# Generated by Django 3.0.5 on 2022-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20220811_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tueform',
            name='fname',
            field=models.CharField(default='user', max_length=30, null=True),
        ),
    ]
