# Generated by Django 3.0.5 on 2022-08-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20220812_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tueform',
            name='addType',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='district',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='name_on_id',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='tueform',
            name='state',
        ),
    ]
