# Generated by Django 3.0.5 on 2022-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20220812_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tueform',
            name='text15',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
