# Generated by Django 3.0.5 on 2022-08-16 11:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0028_auto_20220812_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Questions',
        ),
    ]
