# Generated by Django 3.0.5 on 2022-08-16 11:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0029_auto_20220816_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Task',
        ),
    ]
